WARNING:FaceDetectionService.get_faces-get_faces:Event save_file was not called before
WARNING:FaceDetectionService.get_faces-get_faces:Event delete_file was not called during method execution
WARNING:FaceDetectionService.get_faces-get_faces:File not deleted
WARNING:FaceDetectionService.get_faces-get_faces:Event save_file was not called before
WARNING:FaceDetectionService.get_faces-get_faces:Event delete_file was not called during method execution
WARNING:FaceDetectionService.get_faces-get_faces:File not deleted
WARNING:FaceDetectionService.get_faces-get_faces:Event save_image was not called before
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
ERROR:app:Exception on /detection [POST]
Traceback (most recent call last):
  File "C:\Users\Roxanica\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Roxanica\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Roxanica\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Roxanica\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\app.py", line 24, in detection
    result = FaceDetectionService.get_faces("./temp/" + filename)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\mop\mop_decorators.py", line 60, in wrapper
    return func(*args, **kwargs)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\mop\mop_decorators.py", line 30, in wrapper
    return func(*args, **kwargs)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\mop\mop_decorators.py", line 38, in wrapper
    result = func(*args, **kwargs)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\mop\mop_decorators.py", line 71, in wrapper
    result = func(*args, **kwargs)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\services\face_detection_service.py", line 23, in get_faces
    delete_image(path)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\mop\mop_decorators.py", line 90, in wrapper
    return func(*args, **kwargs)
  File "D:\master\ip\TAIP-2021-2022-PROIECT\face_recognition_module\core\utils.py", line 13, in delete_image
    os.remove(os.path.join('temp', filename))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'temp\\./temp/3086244.jpg'
INFO:werkzeug:127.0.0.1 - - [21/Nov/2021 22:15:14] "[35m[1mPOST /detection HTTP/1.1[0m" 500 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [21/Nov/2021 22:17:58] "POST /detection HTTP/1.1" 200 -
WARNING:FaceDetectionService.get_faces-get_faces:Event save_image was not called before
WARNING:FaceDetectionService.get_faces-get_faces:Event save_image was not called before
WARNING:FaceDetectionService.get_faces-get_faces:Event save_image was not called before
WARNING:FaceDetectionService.get_faces-get_faces:Event save_image was not called before
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:29:03] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:29:28] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:29:32] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:23] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:25] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:26] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:27] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:29] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:33:42] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:34:44] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:34:45] "[33mGET / HTTP/1.1[0m" 404 -
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:45:26] "[31m[1mGET /detection HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:45:27] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:51:17] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:51:27] "POST /detection HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
ERROR:app:Exception on /detection [POST]
Traceback (most recent call last):
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ana\Desktop\TAIP-2021-2022-PROIECT\face_recognition_module\app.py", line 25, in detection
    result = FaceDetectionService.get_faces("./temp/" + filename)
NameError: name 'FaceDetectionService' is not defined
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 19:53:19] "[35m[1mPOST /detection HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
DEBUG:PIL.TiffImagePlugin:tag: ImageWidth (256) - type: short (3) - value: b'\x80\x16'
DEBUG:PIL.TiffImagePlugin:tag: ImageLength (257) - type: short (3) - value: b'\x00\x0f'
DEBUG:PIL.TiffImagePlugin:tag: BitsPerSample (258) - type: short (3) Tag Location: 46 - Data Location: 242 - value: b'\x08\x00\x08\x00\x08\x00'
DEBUG:PIL.TiffImagePlugin:tag: PhotometricInterpretation (262) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: ImageDescription (270) - type: string (2) Tag Location: 70 - Data Location: 248 - value: <table: 217 bytes>
DEBUG:PIL.TiffImagePlugin:tag: Make (271) - type: string (2) Tag Location: 82 - Data Location: 465 - value: b'Canon\x00'
DEBUG:PIL.TiffImagePlugin:tag: Model (272) - type: string (2) Tag Location: 94 - Data Location: 471 - value: b'Canon EOS 5D Mark III\x00'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x01\x00'
DEBUG:PIL.TiffImagePlugin:tag: SamplesPerPixel (277) - type: short (3) - value: b'\x03\x00'
DEBUG:PIL.TiffImagePlugin:tag: XResolution (282) - type: rational (5) Tag Location: 130 - Data Location: 493 - value: b"\xc0\xc6-\x00\x10'\x00\x00"
DEBUG:PIL.TiffImagePlugin:tag: YResolution (283) - type: rational (5) Tag Location: 142 - Data Location: 501 - value: b"\xc0\xc6-\x00\x10'\x00\x00"
DEBUG:PIL.TiffImagePlugin:tag: ResolutionUnit (296) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: Software (305) - type: string (2) Tag Location: 166 - Data Location: 509 - value: <table: 33 bytes>
DEBUG:PIL.TiffImagePlugin:tag: DateTime (306) - type: string (2) Tag Location: 178 - Data Location: 542 - value: b'2020:10:19 15:07:45\x00'
DEBUG:PIL.TiffImagePlugin:tag: Artist (315) - type: string (2) - value: b'FOX\x00'
DEBUG:PIL.TiffImagePlugin:tag: YCbCrPositioning (531) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: Copyright (33432) - type: string (2) Tag Location: 214 - Data Location: 562 - value: b'2015 FOX\x00'
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'<\x02\x00\x00'
DEBUG:PIL.TiffImagePlugin:tag: GPSInfoIFD (34853) - type: long (4) - value: b'\xec\x05\x00\x00'
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sBIT' 41 3
DEBUG:PIL.PngImagePlugin:b'sBIT' 41 3 (unknown)
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 56 8192
ERROR:app:Exception on /detection [POST]
Traceback (most recent call last):
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ana\Desktop\TAIP-2021-2022-PROIECT\face_recognition_module\app.py", line 29, in detection
    face_image = image[coord.top:coord.bottom, coord.left:coord.right]
TypeError: 'FileStorage' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:00:20] "[35m[1mPOST /detection HTTP/1.1[0m" 500 -
ERROR:app:Exception on /detection [POST]
Traceback (most recent call last):
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\ana\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\ana\Desktop\TAIP-2021-2022-PROIECT\face_recognition_module\app.py", line 29, in detection
TypeError: 'FileStorage' object is not subscriptable
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:03:04] "[35m[1mPOST /detection HTTP/1.1[0m" 500 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:05:03] "POST /detection HTTP/1.1" 200 -
DEBUG:PIL.TiffImagePlugin:tag: ImageWidth (256) - type: short (3) - value: b'\x80\x16'
DEBUG:PIL.TiffImagePlugin:tag: ImageLength (257) - type: short (3) - value: b'\x00\x0f'
DEBUG:PIL.TiffImagePlugin:tag: BitsPerSample (258) - type: short (3) Tag Location: 46 - Data Location: 242 - value: b'\x08\x00\x08\x00\x08\x00'
DEBUG:PIL.TiffImagePlugin:tag: PhotometricInterpretation (262) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: ImageDescription (270) - type: string (2) Tag Location: 70 - Data Location: 248 - value: <table: 217 bytes>
DEBUG:PIL.TiffImagePlugin:tag: Make (271) - type: string (2) Tag Location: 82 - Data Location: 465 - value: b'Canon\x00'
DEBUG:PIL.TiffImagePlugin:tag: Model (272) - type: string (2) Tag Location: 94 - Data Location: 471 - value: b'Canon EOS 5D Mark III\x00'
DEBUG:PIL.TiffImagePlugin:tag: Orientation (274) - type: short (3) - value: b'\x01\x00'
DEBUG:PIL.TiffImagePlugin:tag: SamplesPerPixel (277) - type: short (3) - value: b'\x03\x00'
DEBUG:PIL.TiffImagePlugin:tag: XResolution (282) - type: rational (5) Tag Location: 130 - Data Location: 493 - value: b"\xc0\xc6-\x00\x10'\x00\x00"
DEBUG:PIL.TiffImagePlugin:tag: YResolution (283) - type: rational (5) Tag Location: 142 - Data Location: 501 - value: b"\xc0\xc6-\x00\x10'\x00\x00"
DEBUG:PIL.TiffImagePlugin:tag: ResolutionUnit (296) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: Software (305) - type: string (2) Tag Location: 166 - Data Location: 509 - value: <table: 33 bytes>
DEBUG:PIL.TiffImagePlugin:tag: DateTime (306) - type: string (2) Tag Location: 178 - Data Location: 542 - value: b'2020:10:19 15:07:45\x00'
DEBUG:PIL.TiffImagePlugin:tag: Artist (315) - type: string (2) - value: b'FOX\x00'
DEBUG:PIL.TiffImagePlugin:tag: YCbCrPositioning (531) - type: short (3) - value: b'\x02\x00'
DEBUG:PIL.TiffImagePlugin:tag: Copyright (33432) - type: string (2) Tag Location: 214 - Data Location: 562 - value: b'2015 FOX\x00'
DEBUG:PIL.TiffImagePlugin:tag: ExifIFD (34665) - type: long (4) - value: b'<\x02\x00\x00'
DEBUG:PIL.TiffImagePlugin:tag: GPSInfoIFD (34853) - type: long (4) - value: b'\xec\x05\x00\x00'
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:12:31] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:12:31] "[31m[1mGET /detection HTTP/1.1[0m" 405 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:14:31] "[31m[1mGET /detection HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:14:31] "POST /detection HTTP/1.1" 200 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:33:38] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:33:38] "[31m[1mGET /detection HTTP/1.1[0m" 405 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:35:05] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:35:05] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:36:54] "POST /detection HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 20:41:04] "POST /detection HTTP/1.1" 200 -
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
INFO:werkzeug: * Running on http://192.168.1.199:5001/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 21:32:21] "POST /detection HTTP/1.1" 200 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 21:56:49] "POST /detection HTTP/1.1" 200 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 22:00:58] "POST /detection HTTP/1.1" 200 -
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'sRGB' 41 1
DEBUG:PIL.PngImagePlugin:STREAM b'gAMA' 54 4
DEBUG:PIL.PngImagePlugin:STREAM b'pHYs' 70 9
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 91 65445
INFO:werkzeug:127.0.0.1 - - [05/Dec/2021 22:08:57] "POST /detection HTTP/1.1" 200 -
